// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qeaoucacctigdgdzqpgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlYW91Y2FjY3RpZ2RnZHpxcGdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNzUxNTQsImV4cCI6MjA2Nzg1MTE1NH0.VTyrO9X5F4IkPm7Lu--vLpTxdvFZuQhGTg3HR8mrjyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});